global:
  scrape_interval: 10s
  evaluation_interval: 10s
  
rule_files:
 - rules.yml
 
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093
       
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090
 - job_name: node
   static_configs:
    - targets:
       - 35.159.165.253:9100
 - job_name: node_new
   static_configs:
    - targets:
       - 3.122.56.255:9100